### ISSUE TITLE
Can't save/edit formatted numeric fields

### ISSUE THREAD

**Issue by tumainimosha** [mziraki/nova-formatted-number-field#1]
When trying to create or edit a model with formatted numeric fields, I am getting the error

```
The {field_name} must be a number
```
<img width="1099" alt="Screenshot 2019-06-08 at 12 58 13" src="https://user-images.githubusercontent.com/7481490/59145600-e5ac3200-89ee-11e9-90a9-d65b2ab2e322.png">

I am guessing this is due to the comma separator in the number, which are added automatically as part of the formatting.

As a work a work around, I had to create two fields with same name,
1. One which is formatted number, which is hidden in forms, 
2. Another which is not formatted to be displayed in forms

see below

```php
FormattedNumber::make('Price')
    ->exceptOnForms(),

Number::make('Price')
    ->onlyOnForms()
    ->rules('required', 'numeric', 'min:0'),
```

**Comment by mziraki** [comment]
> When trying to create or edit a model with formatted numeric fields, I am getting the error
> 
> ```
> The {field_name} must be a number
> ```
> 
> <img alt="Screenshot 2019-06-08 at 12 58 13" width="1099" src="https://user-images.githubusercontent.com/7481490/59145600-e5ac3200-89ee-11e9-90a9-d65b2ab2e322.png">
> 
> I am guessing this is due to the comma separator in the number, which are added automatically as part of the formatting.
> 
> As a work a work around, I had to create two fields with same name,
> 
> 1. One which is formatted number, which is hidden in forms,
> 2. Another which is not formatted to be displayed in forms
> 
> see below
> 
> ```
> FormattedNumber::make('Price')
>     ->exceptOnForms(),
> 
> Number::make('Price')
>     ->onlyOnForms()
>     ->rules('required', 'numeric', 'min:0'),
> ```

**Comment by mziraki** [comment]
@tumainimosha 
use this in your model:
```php
public function setPriceAttribute($value)
{
    $this->attributes['price'] = $value ? str_replace(',', '', $value) : null;
}
```

**Comment by tumainimosha** [comment]
@mziraki thanks. I ended up using that approach
